'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EmployeeForm.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data is Deleted.
        '''</summary>
        Friend ReadOnly Property MSG_DELETE() As String
            Get
                Return ResourceManager.GetString("MSG_DELETE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to delete this record?.
        '''</summary>
        Friend ReadOnly Property MSG_DELETEERR() As String
            Get
                Return ResourceManager.GetString("MSG_DELETEERR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record cannot be deleted, Try again Later!.
        '''</summary>
        Friend ReadOnly Property MSG_DELETEERROR() As String
            Get
                Return ResourceManager.GetString("MSG_DELETEERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employee Data Deleted.
        '''</summary>
        Friend ReadOnly Property MSG_DELETEHEAD() As String
            Get
                Return ResourceManager.GetString("MSG_DELETEHEAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend ReadOnly Property MSG_ERROR() As String
            Get
                Return ResourceManager.GetString("MSG_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to quit?.
        '''</summary>
        Friend ReadOnly Property MSG_EXIST() As String
            Get
                Return ResourceManager.GetString("MSG_EXIST", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close Application.
        '''</summary>
        Friend ReadOnly Property MSG_EXISTHEAD() As String
            Get
                Return ResourceManager.GetString("MSG_EXISTHEAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UserInput Required.
        '''</summary>
        Friend ReadOnly Property MSG_INPUT() As String
            Get
                Return ResourceManager.GetString("MSG_INPUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Some fields are empty and requires user input.
        '''</summary>
        Friend ReadOnly Property MSG_INPUTERROR() As String
            Get
                Return ResourceManager.GetString("MSG_INPUTERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is created.
        '''</summary>
        Friend ReadOnly Property MSG_INSERT() As String
            Get
                Return ResourceManager.GetString("MSG_INSERT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record cannot be Inserted, Try again Later!.
        '''</summary>
        Friend ReadOnly Property MSG_INSERTERROR() As String
            Get
                Return ResourceManager.GetString("MSG_INSERTERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EmployeeData Insertion.
        '''</summary>
        Friend ReadOnly Property MSG_INSERTHEAD() As String
            Get
                Return ResourceManager.GetString("MSG_INSERTHEAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact Invalid.
        '''</summary>
        Friend ReadOnly Property MSG_INVALDERROR() As String
            Get
                Return ResourceManager.GetString("MSG_INVALDERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Phone Number.
        '''</summary>
        Friend ReadOnly Property MSG_INVALIDPHNO() As String
            Get
                Return ResourceManager.GetString("MSG_INVALIDPHNO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data is Updated.
        '''</summary>
        Friend ReadOnly Property MSG_UPDATE() As String
            Get
                Return ResourceManager.GetString("MSG_UPDATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record cannot be Updated, Try again Later!.
        '''</summary>
        Friend ReadOnly Property MSG_UPDATEERROR() As String
            Get
                Return ResourceManager.GetString("MSG_UPDATEERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Employee Data Updated.
        '''</summary>
        Friend ReadOnly Property MSG_UPDATEHEAD() As String
            Get
                Return ResourceManager.GetString("MSG_UPDATEHEAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export.
        '''</summary>
        Friend ReadOnly Property TXT_BTNEXPORT() As String
            Get
                Return ResourceManager.GetString("TXT_BTNEXPORT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend ReadOnly Property TXT_CLOSEBTN() As String
            Get
                Return ResourceManager.GetString("TXT_CLOSEBTN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit Application.
        '''</summary>
        Friend ReadOnly Property TXT_CLOSETOOLTIP() As String
            Get
                Return ResourceManager.GetString("TXT_CLOSETOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot Found Any Records.
        '''</summary>
        Friend ReadOnly Property TXT_DATAERROR() As String
            Get
                Return ResourceManager.GetString("TXT_DATAERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend ReadOnly Property TXT_DELETEBTN() As String
            Get
                Return ResourceManager.GetString("TXT_DELETEBTN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete Employee.
        '''</summary>
        Friend ReadOnly Property TXT_DELETETOOLTIP() As String
            Get
                Return ResourceManager.GetString("TXT_DELETETOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EmpId.
        '''</summary>
        Friend ReadOnly Property TXT_EMPID() As String
            Get
                Return ResourceManager.GetString("TXT_EMPID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exports the data into files.
        '''</summary>
        Friend ReadOnly Property TXT_EXPORTTOOLTIP() As String
            Get
                Return ResourceManager.GetString("TXT_EXPORTTOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Created Successfully.
        '''</summary>
        Friend ReadOnly Property TXT_FILECREATION() As String
            Get
                Return ResourceManager.GetString("TXT_FILECREATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export Data.
        '''</summary>
        Friend ReadOnly Property TXT_FILEHEAD() As String
            Get
                Return ResourceManager.GetString("TXT_FILEHEAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Insert.
        '''</summary>
        Friend ReadOnly Property TXT_INSERTBTN() As String
            Get
                Return ResourceManager.GetString("TXT_INSERTBTN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add New Employee.
        '''</summary>
        Friend ReadOnly Property TXT_INSERTTOOLTIP() As String
            Get
                Return ResourceManager.GetString("TXT_INSERTTOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address:.
        '''</summary>
        Friend ReadOnly Property TXT_LBLADDRESS() As String
            Get
                Return ResourceManager.GetString("TXT_LBLADDRESS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bloodgroup:.
        '''</summary>
        Friend ReadOnly Property TXT_LBLBLOODGROUP() As String
            Get
                Return ResourceManager.GetString("TXT_LBLBLOODGROUP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact:.
        '''</summary>
        Friend ReadOnly Property TXT_LBLCONTACT() As String
            Get
                Return ResourceManager.GetString("TXT_LBLCONTACT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOB:.
        '''</summary>
        Friend ReadOnly Property TXT_LBLDOB() As String
            Get
                Return ResourceManager.GetString("TXT_LBLDOB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EmployeeId:.
        '''</summary>
        Friend ReadOnly Property TXT_LBLEMPID() As String
            Get
                Return ResourceManager.GetString("TXT_LBLEMPID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FirstName.
        '''</summary>
        Friend ReadOnly Property TXT_LBLFNAME() As String
            Get
                Return ResourceManager.GetString("TXT_LBLFNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gender:.
        '''</summary>
        Friend ReadOnly Property TXT_LBLGENDER() As String
            Get
                Return ResourceManager.GetString("TXT_LBLGENDER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EMPLOYEE INFORMATION FORM.
        '''</summary>
        Friend ReadOnly Property TXT_LBLHEAD() As String
            Get
                Return ResourceManager.GetString("TXT_LBLHEAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LastName.
        '''</summary>
        Friend ReadOnly Property TXT_LBLLNAME() As String
            Get
                Return ResourceManager.GetString("TXT_LBLLNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name:.
        '''</summary>
        Friend ReadOnly Property TXT_LBLNAME() As String
            Get
                Return ResourceManager.GetString("TXT_LBLNAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Female.
        '''</summary>
        Friend ReadOnly Property TXT_RBTNFEMALE() As String
            Get
                Return ResourceManager.GetString("TXT_RBTNFEMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Male.
        '''</summary>
        Friend ReadOnly Property TXT_RBTNMALE() As String
            Get
                Return ResourceManager.GetString("TXT_RBTNMALE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Refresh.
        '''</summary>
        Friend ReadOnly Property TXT_REFRESHBTN() As String
            Get
                Return ResourceManager.GetString("TXT_REFRESHBTN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This button will refresh the employees data.
        '''</summary>
        Friend ReadOnly Property TXT_TOOLTIP() As String
            Get
                Return ResourceManager.GetString("TXT_TOOLTIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update.
        '''</summary>
        Friend ReadOnly Property TXT_UPDATEBTN() As String
            Get
                Return ResourceManager.GetString("TXT_UPDATEBTN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update Employees Data.
        '''</summary>
        Friend ReadOnly Property TXT_UPDATETOOLTIP() As String
            Get
                Return ResourceManager.GetString("TXT_UPDATETOOLTIP", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
