//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDashboard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesFR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesFR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeDashboard.Properties.ResourcesFR", typeof(ResourcesFR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les données sont supprimées.
        /// </summary>
        internal static string MSG_DELETE {
            get {
                return ResourceManager.GetString("MSG_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous supprimer cet enregistrement?.
        /// </summary>
        internal static string MSG_DELETEERR {
            get {
                return ResourceManager.GetString("MSG_DELETEERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;enregistrement ne peut pas être supprimé, réessayez plus tard !.
        /// </summary>
        internal static string MSG_DELETEERROR {
            get {
                return ResourceManager.GetString("MSG_DELETEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données sur les employés supprimées.
        /// </summary>
        internal static string MSG_DELETEHEAD {
            get {
                return ResourceManager.GetString("MSG_DELETEHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string MSG_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de vouloir quitter?.
        /// </summary>
        internal static string MSG_EXIST {
            get {
                return ResourceManager.GetString("MSG_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer l&apos;application.
        /// </summary>
        internal static string MSG_EXISTHEAD {
            get {
                return ResourceManager.GetString("MSG_EXISTHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrée utilisateur requise.
        /// </summary>
        internal static string MSG_INPUT {
            get {
                return ResourceManager.GetString("MSG_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certains champs sont vides et nécessitent une saisie de l&apos;utilisateur.
        /// </summary>
        internal static string MSG_INPUTERROR {
            get {
                return ResourceManager.GetString("MSG_INPUTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion des données des employés.
        /// </summary>
        internal static string MSG_INSERHEAD {
            get {
                return ResourceManager.GetString("MSG_INSERHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to est créé.
        /// </summary>
        internal static string MSG_INSERT {
            get {
                return ResourceManager.GetString("MSG_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;enregistrement ne peut pas être inséré, réessayez plus tard !.
        /// </summary>
        internal static string MSG_INSERTERROR {
            get {
                return ResourceManager.GetString("MSG_INSERTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact invalide.
        /// </summary>
        internal static string MSG_INVALDERROR {
            get {
                return ResourceManager.GetString("MSG_INVALDERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de téléphone invalide.
        /// </summary>
        internal static string MSG_INVALIDPHNO {
            get {
                return ResourceManager.GetString("MSG_INVALIDPHNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les données sont mises à jour.
        /// </summary>
        internal static string MSG_UPDATE {
            get {
                return ResourceManager.GetString("MSG_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;enregistrement ne peut pas être mis à jour, réessayez plus tard !.
        /// </summary>
        internal static string MSG_UPDATEERROR {
            get {
                return ResourceManager.GetString("MSG_UPDATEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données sur les employés mises à jour.
        /// </summary>
        internal static string MSG_UPDATEHEAD {
            get {
                return ResourceManager.GetString("MSG_UPDATEHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string TXT_CLOSEBTN {
            get {
                return ResourceManager.GetString("TXT_CLOSEBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre à jour.
        /// </summary>
        internal static string TXT_DELETEBTN {
            get {
                return ResourceManager.GetString("TXT_DELETEBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identité de l&apos;employé.
        /// </summary>
        internal static string TXT_EMPID {
            get {
                return ResourceManager.GetString("TXT_EMPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insérer.
        /// </summary>
        internal static string TXT_INSERTBTN {
            get {
                return ResourceManager.GetString("TXT_INSERTBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse:.
        /// </summary>
        internal static string TXT_LBLADDRESS {
            get {
                return ResourceManager.GetString("TXT_LBLADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groupe sanguin:.
        /// </summary>
        internal static string TXT_LBLBLOODGROUP {
            get {
                return ResourceManager.GetString("TXT_LBLBLOODGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de contact:.
        /// </summary>
        internal static string TXT_LBLCONTACT {
            get {
                return ResourceManager.GetString("TXT_LBLCONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de naissance:.
        /// </summary>
        internal static string TXT_LBLDOB {
            get {
                return ResourceManager.GetString("TXT_LBLDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro d&apos;employé:.
        /// </summary>
        internal static string TXT_LBLEMPID {
            get {
                return ResourceManager.GetString("TXT_LBLEMPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        internal static string TXT_LBLFNAME {
            get {
                return ResourceManager.GetString("TXT_LBLFNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le sexe:.
        /// </summary>
        internal static string TXT_LBLGENDER {
            get {
                return ResourceManager.GetString("TXT_LBLGENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulaire d&apos;employé.
        /// </summary>
        internal static string TXT_LBLHEAD {
            get {
                return ResourceManager.GetString("TXT_LBLHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de famille.
        /// </summary>
        internal static string TXT_LBLLNAME {
            get {
                return ResourceManager.GetString("TXT_LBLLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom:.
        /// </summary>
        internal static string TXT_LBLNAME {
            get {
                return ResourceManager.GetString("TXT_LBLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femme.
        /// </summary>
        internal static string TXT_RBTNFEMALE {
            get {
                return ResourceManager.GetString("TXT_RBTNFEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mâle.
        /// </summary>
        internal static string TXT_RBTNMALE {
            get {
                return ResourceManager.GetString("TXT_RBTNMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafraîchir.
        /// </summary>
        internal static string TXT_REFRESHBTN {
            get {
                return ResourceManager.GetString("TXT_REFRESHBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce bouton actualisera les données des employés.
        /// </summary>
        internal static string TXT_TOOLTIP {
            get {
                return ResourceManager.GetString("TXT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        internal static string TXT_UPDATEBTN {
            get {
                return ResourceManager.GetString("TXT_UPDATEBTN", resourceCulture);
            }
        }
    }
}
