//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDashboard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesRU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesRU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeDashboard.Properties.ResourcesRU", typeof(ResourcesRU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные удалены.
        /// </summary>
        internal static string MSG_DELETE {
            get {
                return ResourceManager.GetString("MSG_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите удалить эту запись?.
        /// </summary>
        internal static string MSG_DELETEERR {
            get {
                return ResourceManager.GetString("MSG_DELETEERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись не может быть удалена, попробуйте позже!.
        /// </summary>
        internal static string MSG_DELETEERROR {
            get {
                return ResourceManager.GetString("MSG_DELETEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные сотрудника удалены.
        /// </summary>
        internal static string MSG_DELETEHEAD {
            get {
                return ResourceManager.GetString("MSG_DELETEHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string MSG_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите выйти?.
        /// </summary>
        internal static string MSG_EXIST {
            get {
                return ResourceManager.GetString("MSG_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть приложение.
        /// </summary>
        internal static string MSG_EXISTHEAD {
            get {
                return ResourceManager.GetString("MSG_EXISTHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется пользовательский ввод.
        /// </summary>
        internal static string MSG_INPUT {
            get {
                return ResourceManager.GetString("MSG_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоторые поля пусты и требуют ввода пользователем.
        /// </summary>
        internal static string MSG_INPUTERROR {
            get {
                return ResourceManager.GetString("MSG_INPUTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставка данных о сотрудниках.
        /// </summary>
        internal static string MSG_INSERHEAD {
            get {
                return ResourceManager.GetString("MSG_INSERHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to создано.
        /// </summary>
        internal static string MSG_INSERT {
            get {
                return ResourceManager.GetString("MSG_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись не может быть вставлена, попробуйте позже!.
        /// </summary>
        internal static string MSG_INSERTERROR {
            get {
                return ResourceManager.GetString("MSG_INSERTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакт недействителен.
        /// </summary>
        internal static string MSG_INVALDERROR {
            get {
                return ResourceManager.GetString("MSG_INVALDERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный номер телефона.
        /// </summary>
        internal static string MSG_INVALIDPHNO {
            get {
                return ResourceManager.GetString("MSG_INVALIDPHNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные обновлены.
        /// </summary>
        internal static string MSG_UPDATE {
            get {
                return ResourceManager.GetString("MSG_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись не может быть обновлена, попробуйте позже!.
        /// </summary>
        internal static string MSG_UPDATEERROR {
            get {
                return ResourceManager.GetString("MSG_UPDATEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные о сотрудниках обновлены.
        /// </summary>
        internal static string MSG_UPDATEHEAD {
            get {
                return ResourceManager.GetString("MSG_UPDATEHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрывать.
        /// </summary>
        internal static string TXT_CLOSEBTN {
            get {
                return ResourceManager.GetString("TXT_CLOSEBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновлять.
        /// </summary>
        internal static string TXT_DELETEBTN {
            get {
                return ResourceManager.GetString("TXT_DELETEBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to личность сотрудника.
        /// </summary>
        internal static string TXT_EMPID {
            get {
                return ResourceManager.GetString("TXT_EMPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставлять.
        /// </summary>
        internal static string TXT_INSERTBTN {
            get {
                return ResourceManager.GetString("TXT_INSERTBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес:.
        /// </summary>
        internal static string TXT_LBLADDRESS {
            get {
                return ResourceManager.GetString("TXT_LBLADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа крови:.
        /// </summary>
        internal static string TXT_LBLBLOODGROUP {
            get {
                return ResourceManager.GetString("TXT_LBLBLOODGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактный номер:.
        /// </summary>
        internal static string TXT_LBLCONTACT {
            get {
                return ResourceManager.GetString("TXT_LBLCONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения:.
        /// </summary>
        internal static string TXT_LBLDOB {
            get {
                return ResourceManager.GetString("TXT_LBLDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Число работников:.
        /// </summary>
        internal static string TXT_LBLEMPID {
            get {
                return ResourceManager.GetString("TXT_LBLEMPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string TXT_LBLFNAME {
            get {
                return ResourceManager.GetString("TXT_LBLFNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол:.
        /// </summary>
        internal static string TXT_LBLGENDER {
            get {
                return ResourceManager.GetString("TXT_LBLGENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма сотрудника.
        /// </summary>
        internal static string TXT_LBLHEAD {
            get {
                return ResourceManager.GetString("TXT_LBLHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        internal static string TXT_LBLLNAME {
            get {
                return ResourceManager.GetString("TXT_LBLLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя:.
        /// </summary>
        internal static string TXT_LBLNAME {
            get {
                return ResourceManager.GetString("TXT_LBLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женский.
        /// </summary>
        internal static string TXT_RBTNFEMALE {
            get {
                return ResourceManager.GetString("TXT_RBTNFEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужчина.
        /// </summary>
        internal static string TXT_RBTNMALE {
            get {
                return ResourceManager.GetString("TXT_RBTNMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string TXT_REFRESHBTN {
            get {
                return ResourceManager.GetString("TXT_REFRESHBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта кнопка обновит данные сотрудников.
        /// </summary>
        internal static string TXT_TOOLTIP {
            get {
                return ResourceManager.GetString("TXT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string TXT_UPDATEBTN {
            get {
                return ResourceManager.GetString("TXT_UPDATEBTN", resourceCulture);
            }
        }
    }
}
