//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDashboard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesUS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesUS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeDashboard.Properties.ResourcesUS", typeof(ResourcesUS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is Deleted.
        /// </summary>
        internal static string MSG_DELETE {
            get {
                return ResourceManager.GetString("MSG_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this record?.
        /// </summary>
        internal static string MSG_DELETEERR {
            get {
                return ResourceManager.GetString("MSG_DELETEERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record cannot be deleted, Try again Later!.
        /// </summary>
        internal static string MSG_DELETEERROR {
            get {
                return ResourceManager.GetString("MSG_DELETEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Data Deleted.
        /// </summary>
        internal static string MSG_DELETEHEAD {
            get {
                return ResourceManager.GetString("MSG_DELETEHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MSG_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit?.
        /// </summary>
        internal static string MSG_EXIST {
            get {
                return ResourceManager.GetString("MSG_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Application.
        /// </summary>
        internal static string MSG_EXISTHEAD {
            get {
                return ResourceManager.GetString("MSG_EXISTHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInput Required.
        /// </summary>
        internal static string MSG_INPUT {
            get {
                return ResourceManager.GetString("MSG_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields are empty and requires user input.
        /// </summary>
        internal static string MSG_INPUTERROR {
            get {
                return ResourceManager.GetString("MSG_INPUTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeData Insertion.
        /// </summary>
        internal static string MSG_INSERHEAD {
            get {
                return ResourceManager.GetString("MSG_INSERHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is created.
        /// </summary>
        internal static string MSG_INSERT {
            get {
                return ResourceManager.GetString("MSG_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record cannot be Inserted, Try again Later!.
        /// </summary>
        internal static string MSG_INSERTERROR {
            get {
                return ResourceManager.GetString("MSG_INSERTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Invalid.
        /// </summary>
        internal static string MSG_INVALDERROR {
            get {
                return ResourceManager.GetString("MSG_INVALDERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone Number.
        /// </summary>
        internal static string MSG_INVALIDPHNO {
            get {
                return ResourceManager.GetString("MSG_INVALIDPHNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is Updated.
        /// </summary>
        internal static string MSG_UPDATE {
            get {
                return ResourceManager.GetString("MSG_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record cannot be Updated, Try again Later!.
        /// </summary>
        internal static string MSG_UPDATEERROR {
            get {
                return ResourceManager.GetString("MSG_UPDATEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Data Updated.
        /// </summary>
        internal static string MSG_UPDATEHEAD {
            get {
                return ResourceManager.GetString("MSG_UPDATEHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string TXT_CLOSEBTN {
            get {
                return ResourceManager.GetString("TXT_CLOSEBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string TXT_DELETEBTN {
            get {
                return ResourceManager.GetString("TXT_DELETEBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmpId.
        /// </summary>
        internal static string TXT_EMPID {
            get {
                return ResourceManager.GetString("TXT_EMPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string TXT_INSERTBTN {
            get {
                return ResourceManager.GetString("TXT_INSERTBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string TXT_LBLADDRESS {
            get {
                return ResourceManager.GetString("TXT_LBLADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloodgroup:.
        /// </summary>
        internal static string TXT_LBLBLOODGROUP {
            get {
                return ResourceManager.GetString("TXT_LBLBLOODGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        internal static string TXT_LBLCONTACT {
            get {
                return ResourceManager.GetString("TXT_LBLCONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB:.
        /// </summary>
        internal static string TXT_LBLDOB {
            get {
                return ResourceManager.GetString("TXT_LBLDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeId:.
        /// </summary>
        internal static string TXT_LBLEMPID {
            get {
                return ResourceManager.GetString("TXT_LBLEMPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        internal static string TXT_LBLFNAME {
            get {
                return ResourceManager.GetString("TXT_LBLFNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender:.
        /// </summary>
        internal static string TXT_LBLGENDER {
            get {
                return ResourceManager.GetString("TXT_LBLGENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPLOYEE INFORMATION FORM.
        /// </summary>
        internal static string TXT_LBLHEAD {
            get {
                return ResourceManager.GetString("TXT_LBLHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        internal static string TXT_LBLLNAME {
            get {
                return ResourceManager.GetString("TXT_LBLLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string TXT_LBLNAME {
            get {
                return ResourceManager.GetString("TXT_LBLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string TXT_RBTNFEMALE {
            get {
                return ResourceManager.GetString("TXT_RBTNFEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string TXT_RBTNMALE {
            get {
                return ResourceManager.GetString("TXT_RBTNMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string TXT_REFRESHBTN {
            get {
                return ResourceManager.GetString("TXT_REFRESHBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button will refresh the employees data.
        /// </summary>
        internal static string TXT_TOOLTIP {
            get {
                return ResourceManager.GetString("TXT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TXT_UPDATEBTN {
            get {
                return ResourceManager.GetString("TXT_UPDATEBTN", resourceCulture);
            }
        }
    }
}
