//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDashboard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesDE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesDE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeeDashboard.Properties.ResourcesDE", typeof(ResourcesDE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten werden gelöscht.
        /// </summary>
        internal static string MSG_DELETE {
            get {
                return ResourceManager.GetString("MSG_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie diesen Datensatz löschen?.
        /// </summary>
        internal static string MSG_DELETEERR {
            get {
                return ResourceManager.GetString("MSG_DELETEERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensatz kann nicht gelöscht werden, versuchen Sie es später erneut!.
        /// </summary>
        internal static string MSG_DELETEERROR {
            get {
                return ResourceManager.GetString("MSG_DELETEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitarbeiterdaten gelöscht.
        /// </summary>
        internal static string MSG_DELETEHEAD {
            get {
                return ResourceManager.GetString("MSG_DELETEHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string MSG_ERROR {
            get {
                return ResourceManager.GetString("MSG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie aufhören wollen?.
        /// </summary>
        internal static string MSG_EXIST {
            get {
                return ResourceManager.GetString("MSG_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließe die Anwendung.
        /// </summary>
        internal static string MSG_EXISTHEAD {
            get {
                return ResourceManager.GetString("MSG_EXISTHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzereingabe erforderlich.
        /// </summary>
        internal static string MSG_INPUT {
            get {
                return ResourceManager.GetString("MSG_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einige Felder sind leer und erfordern Benutzereingaben.
        /// </summary>
        internal static string MSG_INPUTERROR {
            get {
                return ResourceManager.GetString("MSG_INPUTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfügen von Mitarbeiterdaten.
        /// </summary>
        internal static string MSG_INSERHEAD {
            get {
                return ResourceManager.GetString("MSG_INSERHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is created.
        /// </summary>
        internal static string MSG_INSERT {
            get {
                return ResourceManager.GetString("MSG_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to geschaffen.
        /// </summary>
        internal static string MSG_INSERTERROR {
            get {
                return ResourceManager.GetString("MSG_INSERTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt Ungültig.
        /// </summary>
        internal static string MSG_INVALDERROR {
            get {
                return ResourceManager.GetString("MSG_INVALDERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültige Telefonnummer.
        /// </summary>
        internal static string MSG_INVALIDPHNO {
            get {
                return ResourceManager.GetString("MSG_INVALIDPHNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten werden aktualisiert.
        /// </summary>
        internal static string MSG_UPDATE {
            get {
                return ResourceManager.GetString("MSG_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datensatz kann nicht aktualisiert werden, versuchen Sie es später erneut!.
        /// </summary>
        internal static string MSG_UPDATEERROR {
            get {
                return ResourceManager.GetString("MSG_UPDATEERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitarbeiterdaten aktualisiert.
        /// </summary>
        internal static string MSG_UPDATEHEAD {
            get {
                return ResourceManager.GetString("MSG_UPDATEHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nah dran.
        /// </summary>
        internal static string TXT_CLOSEBTN {
            get {
                return ResourceManager.GetString("TXT_CLOSEBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren.
        /// </summary>
        internal static string TXT_DELETEBTN {
            get {
                return ResourceManager.GetString("TXT_DELETEBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitarbeiteridentität.
        /// </summary>
        internal static string TXT_EMPID {
            get {
                return ResourceManager.GetString("TXT_EMPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfügung.
        /// </summary>
        internal static string TXT_INSERTBTN {
            get {
                return ResourceManager.GetString("TXT_INSERTBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse:.
        /// </summary>
        internal static string TXT_LBLADDRESS {
            get {
                return ResourceManager.GetString("TXT_LBLADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blutgruppe:.
        /// </summary>
        internal static string TXT_LBLBLOODGROUP {
            get {
                return ResourceManager.GetString("TXT_LBLBLOODGROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt Nummer:.
        /// </summary>
        internal static string TXT_LBLCONTACT {
            get {
                return ResourceManager.GetString("TXT_LBLCONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geburtsdatum:.
        /// </summary>
        internal static string TXT_LBLDOB {
            get {
                return ResourceManager.GetString("TXT_LBLDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitarbeiternummer:.
        /// </summary>
        internal static string TXT_LBLEMPID {
            get {
                return ResourceManager.GetString("TXT_LBLEMPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        internal static string TXT_LBLFNAME {
            get {
                return ResourceManager.GetString("TXT_LBLFNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschlecht:.
        /// </summary>
        internal static string TXT_LBLGENDER {
            get {
                return ResourceManager.GetString("TXT_LBLGENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitarbeiterformular.
        /// </summary>
        internal static string TXT_LBLHEAD {
            get {
                return ResourceManager.GetString("TXT_LBLHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familienname.
        /// </summary>
        internal static string TXT_LBLLNAME {
            get {
                return ResourceManager.GetString("TXT_LBLLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string TXT_LBLNAME {
            get {
                return ResourceManager.GetString("TXT_LBLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiblich.
        /// </summary>
        internal static string TXT_RBTNFEMALE {
            get {
                return ResourceManager.GetString("TXT_RBTNFEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Männlich.
        /// </summary>
        internal static string TXT_RBTNMALE {
            get {
                return ResourceManager.GetString("TXT_RBTNMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisierung.
        /// </summary>
        internal static string TXT_REFRESHBTN {
            get {
                return ResourceManager.GetString("TXT_REFRESHBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Schaltfläche aktualisiert die Mitarbeiterdaten.
        /// </summary>
        internal static string TXT_TOOLTIP {
            get {
                return ResourceManager.GetString("TXT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string TXT_UPDATEBTN {
            get {
                return ResourceManager.GetString("TXT_UPDATEBTN", resourceCulture);
            }
        }
    }
}
